query gardenById($id: ID!) {
  garden(id: $id) {
    id
    parcels {
      id
      name
      geometry
      cultivableArea
      area
      beds {
        id
        geometry
      }
      soilType {
        code
        description
        area
        proportion
      }
    }
  }
}

query gardens {
  gardens {
    id
    name
  }
}

query garden($id: ID!) {
  garden(id: $id) {
    id
  }
}
