query gardenById($id: ID!) {
  garden(id: $id) {
    id
    parcelSet {
      id
      name
      geometry
      cultivableArea
      area
      bedSet {
        id
        geometry
      }
      soilType {
        code
        description
        area
        proportion
      }
    }
  }
}
