mutation deleteParcel($id: ID!) {
  deleteParcel(id: $id) {
    ok
  }
}

query parcelsFromGardenId($id: ID!) {
  garden(id: $id) {
    id
    parcelSet {
      id
      name
      geometry
      bedSet {
        id
        geometry
      }
    }
  }
}

query getParcelDetails($id: ID!) {
  parceldetails: parcel(id: $id) {
    id
    area
    cultivableArea
    soilType {
      code
      description
      proportion
    }
  }
}

mutation createParcel($name: String!, $geometry: String!, $gardenId: ID!) {
  createParcel(name: $name, geometry: $geometry, gardenId: $gardenId) {
    id
    name
    geometry
    bedSet {
      id
      geometry
    }
  }
}

mutation updateParcel($geometry: String, $id: ID!) {
  updateParcel(geometry: $geometry, id: $id) {
    id
    name
    geometry
  }
}
